language: go
os: linux
go:
  - "1.19"
arch:
  - amd64
git:
  depth: 1
before_install:
  - go get github.com/rodolfoap/gx
# Buggy!
#before_script:
#  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.37.1
script:
  # https://github.com/golangci/golangci-lint/pull/620/files
  #- go mod download
  #- golangci-lint run
  - go test -v -covermode=count -coverprofile=profile.cov
after_success:
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=circle-ci
notifications:
  email:
    recipients:
      - rodolfoap@live.com
    on_success: change
    on_failure: always
