language: go
os: linux
go:
  - "1.19"
arch:
  - amd64
git:
  depth: 1
before_install:
  - go get github.com/rodolfoap/gx
script:
  - export BDEBUG=1
  - go test -v -covermode=count -coverprofile=profile.cov
after_success:
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=circle-ci
notifications:
  email:
    recipients:
      - rodolfoap@live.com
    on_success: change
    on_failure: always
